### PR TITLE
Heroku style

### PR DESCRIPTION
**Pull request by davidgatti**

### CODE REVIEW

**Comment by Serhii-Hulko** [comment]
@davidgatti can you check my changes?

**Comment by davidgatti** [comment]
@Serhii-Hulko 

- Lets agree on tabs instead of spaces, otherwise there is going to irrelevant changes tracked by Git.
- It be nice if you kept the comment style in the JS section the same 

Questions for @aabony to decide on.

- on the video page there is this message in red: `After recording, you must hit the upload button to save your new video.`. This is not true, once you stop the recording all is good, and you have to just click next. 
- on the resume page: once the file is uploaded I automatically redirect the user to the thank you page. so the `Submit` button is never used. Either we can remove the button, or I can disable the auto redirect.

**Comment by davidgatti** [comment]
OK, this branch is deployed at https://dev.teachpart-time.com/ for everyone to play with.

@aabony do you want to to:

- Skip the video if already present
- Skip the Resume if already present

When you come from a Draft URL?

**Comment by aabony** [comment]
Hi @davidgatti , let me add this question to our technical debt list and get back to you. In meantime, one issue to fix: One the resume page, when a user chooses the file, can we just have the plugin upload the file automatically, instead of having to hit upload? Secondly, upon hitting upload, the form automatically submits, we should simply alow the user to hit submit once theyve uploaded the file.

**Comment by aabony** [comment]
also, can someone quickly change this @davidgatti or @Serhii-Hulko  from City&state/province to just City, and inside the form field just write Salt Lake City ? thanks!


image

**Comment by aabony** [comment]
also can we remove this area from the design @Serhii-Hulko  @davidgatti 


image

**Comment by aabony** [comment]
hi @davidgatti  on the resume page submit, lets turn of the auto-redirect, and use the submit button so the user can complete. its the best user experience. thanks

**Comment by davidgatti** [comment]
@aabony OK, I changed how the upload form works. Now the flow is like this:

- You select the file
- The page will start the upload automatically
- Once the upload is done the submit button becomes active.

@Serhii-Hulko I did incorporate your JS snippet to show the name of the selected file in to my listener, so there is just one listener that checks for file selects.

**Pull request merged**
